---
title: "B2.592_TFM_Análisis de negocio_Eduard Abella Curiel"
author: "Eduard Abella Curiel"
date: "26 abril de 2019"
output: html_document
---

```{r}
library("readxl")
x<-read_excel("TFM_Telco Churn dataset.xlsx")
x <- as.data.frame(x)
```
```{r}
summary (x)
f1 <- hist(x$tenure, main="Histograma Permanencia", col = "gray", labels = TRUE)
f1
f2 <- hist(x$TotalCall, main="Histograma Llamadas", col = "gray", labels = TRUE)
f2
f3 <- hist(x$TotalRevenue, main="Histograma Ingresos", col = "gray", labels = TRUE)
f3
cor(x[,c("tenure","TotalCall","TotalRevenue")], use="complete")
```
```{r}
## Caràcters a factors

for (i in 1:ncol(x)) {
  
  if(class(x[,i])=="character") {x[,i] <- as.factor(x[,i])}
  
}

  x[,3] <- as.factor(x[,3])
  
  ## Eliminar files amb missings
  
  x <- x[complete.cases(x),]

  ## Eliminar columnes amb informació igual per a tots els individus (phone service) i columna ID
  
  x <- x[,-c(1,7)]
  
```




```{r}
install.packages("randomForest")
library(randomForest)

set.seed(1)
train <- sample(1:nrow(x), rep=F, size=round((2/3)*nrow(x)))
test<- which(!1:3328%in%train)

x.train <- x[train,]
x.test <- x[test,]

set.seed(11)
z <- randomForest(Churn ~ ., data=x.train, ntree=10)
prediccions <- predict(z,x.test)
table(x.test[,18],prediccions)

## Per fer chi^2 -> para ver dependencias entre 2 variables categóricas
##gender
table(x$Churn, x$gender)
chisq.test(table(x$Churn, x$gender))
## p-value > 0,05, no puedo rechazar la H0, por lo que la variable gender es independiente del churn, por lo que la puedo eliminar de mi análisis.

##SeniorCitizen
table(x$Churn, x$SeniorCitizen)
chisq.test(table(x$Churn, x$SeniorCitizen))
## Si p-value < 0,05, puedo rechazar la H0, por lo que la variable SeniorCitizen es dependiente del churn, por lo que NO la puedo eliminar de mi análisis.

##MaritalStatus
table(x$Churn, x$MaritalStatus)
chisq.test(table(x$Churn, x$MaritalStatus))
## Si p-value < 0,05, puedo rechazar la H0, por lo que la variable MaritalStatus es dependiente del churn, por lo que NO la puedo eliminar de mi análisis.

##Dependents
table(x$Churn, x$Dependents)
chisq.test(table(x$Churn, x$Dependents))
## Si p-value < 0,05, puedo rechazar la H0, por lo que la variable Dependents es dependiente del churn, por lo que NO la puedo eliminar de mi análisis.

##MultipleLines
table(x$Churn, x$MultipleLines)
chisq.test(table(x$Churn, x$MultipleLines))
## Si p-value < 0,05, puedo rechazar la H0, por lo que la variable MultipleLines es dependiente del churn, por lo que NO la puedo eliminar de mi análisis.

##InternetService
table(x$Churn, x$InternetService)
chisq.test(table(x$Churn, x$InternetService))
## Si p-value < 0,05, puedo rechazar la H0, por lo que la variable InternetService es dependiente del churn, por lo que NO la puedo eliminar de mi análisis.

##OnlineSecurity
table(x$Churn, x$OnlineSecurity)
chisq.test(table(x$Churn, x$OnlineSecurity))
## Si p-value < 0,05, puedo rechazar la H0, por lo que la variable OnlineSecurity es dependiente del churn, por lo que NO la puedo eliminar de mi análisis.

##OnlineBackup
table(x$Churn, x$OnlineBackup)
chisq.test(table(x$Churn, x$OnlineBackup))
## Si p-value < 0,05, puedo rechazar la H0, por lo que la variable OnlineBackup es dependiente del churn, por lo que NO la puedo eliminar de mi análisis.

##DeviceProtection
table(x$Churn, x$DeviceProtection)
chisq.test(table(x$Churn, x$DeviceProtection))
## Si p-value < 0,05, puedo rechazar la H0, por lo que la variable DeviceProtection es dependiente del churn, por lo que NO la puedo eliminar de mi análisis.

##TechSupport
table(x$Churn, x$TechSupport)
chisq.test(table(x$Churn, x$TechSupport))
## Si p-value < 0,05, puedo rechazar la H0, por lo que la variable TechSupport es dependiente del churn, por lo que NO la puedo eliminar de mi análisis.

##StreamingTV
table(x$Churn, x$StreamingTV)
chisq.test(table(x$Churn, x$StreamingTV))
## Si p-value < 0,05, puedo rechazar la H0, por lo que la variable StreamingTV es dependiente del churn, por lo que NO la puedo eliminar de mi análisis.

##StreamingMovies
table(x$Churn, x$StreamingMovies)
chisq.test(table(x$Churn, x$StreamingMovies))
## Si p-value < 0,05, puedo rechazar la H0, por lo que la variable StreamingMovies es dependiente del churn, por lo que NO la puedo eliminar de mi análisis.

##StreamingMovies
table(x$Churn, x$StreamingMovies)
chisq.test(table(x$Churn, x$StreamingMovies))
## Si p-value < 0,05, puedo rechazar la H0, por lo que la variable StreamingMovies es dependiente del churn, por lo que NO la puedo eliminar de mi análisis.

##Contract
table(x$Churn, x$Contract)
chisq.test(table(x$Churn, x$Contract))
## Si p-value < 0,05, puedo rechazar la H0, por lo que la variable Contract es dependiente del churn, por lo que NO la puedo eliminar de mi análisis.

##PaperlessBilling
table(x$Churn, x$PaperlessBilling)
chisq.test(table(x$Churn, x$PaperlessBilling))
## Si p-value < 0,05, puedo rechazar la H0, por lo que la variable PaperlessBilling es dependiente del churn, por lo que NO la puedo eliminar de mi análisis.

##PaymentMethod
table(x$Churn, x$PaymentMethod)
chisq.test(table(x$Churn, x$PaymentMethod))
## Si p-value < 0,05, puedo rechazar la H0, por lo que la variable PaymentMethod es dependiente del churn, por lo que NO la puedo eliminar de mi análisis.

##InternationalPlan
table(x$Churn, x$InternationalPlan)
chisq.test(table(x$Churn, x$InternationalPlan))
## Si p-value < 0,05, puedo rechazar la H0, por lo que la variable InternationalPlan es dependiente del churn, por lo que NO la puedo eliminar de mi análisis.

##VoiceMailPlan
table(x$Churn, x$VoiceMailPlan)
chisq.test(table(x$Churn, x$VoiceMailPlan))
## Si p-value < 0,05, puedo rechazar la H0, por lo que la variable VoiceMailPlan es dependiente del churn, por lo que NO la puedo eliminar de mi análisis.


##Per fer t.test -> para ver dependencias entre 2 variables categóricas
##tenure
t.test(tenure~Churn, data=x)
## Si p-value < 0,05, puedo rechazar la H0, por lo que la variable tenure es dependiente del churn, por lo que NO la puedo eliminar de mi análisis.
 
##NumbervMailMessages
t.test(NumbervMailMessages~Churn, data=x)
## Si p-value < 0,05, puedo rechazar la H0, por lo que la variable NumbervMailMessages es dependiente del churn, por lo que NO la puedo eliminar de mi análisis.
 
##TotalDayMinutes
t.test(TotalDayMinutes~Churn, data=x)
## Si p-value < 0,05, puedo rechazar la H0, por lo que la variable TotalDayMinutes es dependiente del churn, por lo que NO la puedo eliminar de mi análisis.
 
##TotalDayCalls
t.test(TotalDayCalls~Churn, data=x)
## Si p-value > 0,05, no puedo rechazar la H0, por lo que la variable TotalDayCalls es independiente del churn, por lo que la puedo eliminar de mi análisis.

 ##TotalEveMinutes
t.test(TotalEveMinutes~Churn, data=x)
## Si p-value < 0,05, puedo rechazar la H0, por lo que la variable TotalEveMinutes es dependiente del churn, por lo que NO la puedo eliminar de mi análisis.

 ##TotalEveCalls
t.test(TotalEveCalls~Churn, data=x)
## Si p-value > 0,05, no puedo rechazar la H0, por lo que la variable TotalEveCalls es independiente del churn, por lo que la puedo eliminar de mi análisis.

 ##TotalNightMinutes
t.test(TotalNightMinutes~Churn, data=x)
## Si p-value < 0,05, puedo rechazar la H0, por lo que la variable TotalNightMinutes es dependiente del churn, por lo que NO la puedo eliminar de mi análisis.

 ##TotalNightCalls
t.test(TotalNightCalls~Churn, data=x)
## Si p-value > 0,05, no puedo rechazar la H0, por lo que la variable TotalNightCalls es independiente del churn, por lo que la puedo eliminar de mi análisis.

 ##TotalIntlMinutes
t.test(TotalIntlMinutes~Churn, data=x)
## Si p-value < 0,05, puedo rechazar la H0, por lo que la variable TotalIntlMinutes es dependiente del churn, por lo que NO la puedo eliminar de mi análisis.

 ##TotalIntlCalls
t.test(TotalIntlCalls~Churn, data=x)
## Si p-value < 0,05, puedo rechazar la H0, por lo que la variable TotalIntlCalls es dependiente del churn, por lo que NO la puedo eliminar de mi análisis.

 ##CustomerServiceCalls
t.test(CustomerServiceCalls~Churn, data=x)
## Si p-value < 0,05, puedo rechazar la H0, por lo que la variable CustomerServiceCalls es dependiente del churn, por lo que NO la puedo eliminar de mi análisis.

 ##TotalCall
t.test(TotalCall~Churn, data=x)
## Si p-value > 0,05, no puedo rechazar la H0, por lo que la variable TotalCall es independiente del churn, por lo que la puedo eliminar de mi análisis.

 ##TotalRevenue
t.test(TotalRevenue~Churn, data=x)
## Si p-value < 0,05, puedo rechazar la H0, por lo que la variable TotalRevenue es dependiente del churn, por lo que NO la puedo eliminar de mi análisis.



##CONCLUSIÓN:
##Podemos eliminar Gender, TotalDayCalls, TotalEveCalls, TotalNightCalls y TotalCall
m <- x[,-c(1,21,23,25,29)] ##quitamos columnas
gow.mat <- vegdist(as.numeric(unlist(x)), method="gower")
```

